### ISSUE TITLE
LCD setup menu error related to bed mesh

### ISSUE THREAD

**Issue by scmanjarrez** [jschuh/klipper-macros#34]
Do I need custom hardware to use your LCD menus? I'm using stock display from ender3 (12864)

```python                                                                                                  
Error evaluating 'menu __main __setup __bed_surface:input': ValueError: '' is not in list                                                                                                     
Traceback (most recent call last):                                                                                                                                                            
  File "/home/printer/klipper/klipper/klippy/extras/gcode_macro.py", line 61, in render                                                                                                       
    return str(self.template.render(context))                                                                                                                                                 
  File "/home/printer/klipper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render                                                                                   
    self.environment.handle_exception()                                                                                                                                                       
  File "/home/printer/klipper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception                                                                          
    reraise(*rewrite_traceback_stack(source=source))                                                                                                                                          
  File "/home/printer/klipper/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise                                                                                        
    raise value.with_traceback(tb)                                                                                                                                                            
  File "<template>", line 2, in top-level template code                                                                                                                                       
ValueError: '' is not in list
List drawing error
Traceback (most recent call last):
  File "/home/printer/klipper/klipper/klippy/extras/gcode_macro.py", line 61, in render
    return str(self.template.render(context))
  File "/home/printer/klipper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/printer/klipper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/printer/klipper/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
ValueError: '' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/printer/klipper/klipper/klippy/extras/display/menu.py", line 625, in draw_container
    text = current.render_name(selected)
  File "/home/printer/klipper/klipper/klippy/extras/display/menu.py", line 164, in render_name
    name = str(self._render_name())
  File "/home/printer/klipper/klipper/klippy/extras/display/menu.py", line 66, in _render_name
    context = self.get_context()
  File "/home/printer/klipper/klipper/klippy/extras/display/menu.py", line 488, in get_context
    value = (self._eval_value(context) if self._input_value is None
  File "/home/printer/klipper/klipper/klippy/extras/display/menu.py", line 521, in _eval_value
    self._input_tpl.render(context)))
  File "/home/printer/klipper/klipper/klippy/extras/gcode_macro.py", line 66, in render
    raise self.gcode.error(msg)
gcode.CommandError: Error evaluating 'menu __main __setup __bed_surface:input': ValueError: '' is not in list
```

printer.cfg
```
# This file contains common pin mappings for the 2018 Creality
# Ender 3. To use this config, the firmware should be compiled for the
# AVR atmega1284p.

# Note, a number of Melzi boards are shipped with a bootloader that
# requires the following command to flash the board:
#  avrdude -p atmega1284p -c arduino -b 57600 -P /dev/ttyUSB0 -U out/klipper.elf.hex
# If the above command does not work and "make flash" does not work
# then one may need to flash a bootloader to the board - see the
# Klipper docs/Bootloaders.md file for more information.

# See docs/Config_Reference.md for a description of parameters.

[stepper_x]
step_pin: ar54
dir_pin: !ar55
enable_pin: !ar38
microsteps: 16
rotation_distance: 40
endstop_pin: ^ar3
position_min: -3
position_endstop: -3
position_max: 250
homing_speed: 50

[stepper_y]
step_pin: ar60
dir_pin: !ar61
enable_pin: !ar56
microsteps: 16
rotation_distance: 40
endstop_pin: ^ar14
position_min: -6
position_endstop: -6
position_max: 235
homing_speed: 50

[stepper_z]
step_pin: ar46
dir_pin: ar48
enable_pin: !ar62
microsteps: 16
rotation_distance: 7.96
endstop_pin: probe:z_virtual_endstop
position_max: 250
position_min: -3

[extruder]
step_pin: ar26
dir_pin: !ar28
enable_pin: !ar24
max_extrude_only_distance: 420.0
min_extrude_temp: 170
microsteps: 16
rotation_distance: 7.71
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: ar10
sensor_type: EPCOS 100K B57560G104F
sensor_pin: analog13
pressure_advance = 0.5
min_temp: 0
max_temp: 250

[heater_bed]
heater_pin: ar8
sensor_type: EPCOS 100K B57560G104F
sensor_pin: analog14
min_temp: 0
max_temp: 130

[tmc2208 stepper_x]
uart_pin: ar40
interpolate: True
run_current: 0.580
sense_resistor: 0.11
stealthchop_threshold: 150

[tmc2208 stepper_y]
uart_pin: ar59
interpolate: True
run_current: 0.580
sense_resistor: 0.11
stealthchop_threshold: 150

[tmc2208 stepper_z]
uart_pin: ar42
interpolate: True
run_current: 0.580
sense_resistor: 0.11
stealthchop_threshold: 150

[tmc2208 extruder]
uart_pin: ar44
interpolate: True
run_current: 0.650
sense_resistor: 0.11
stealthchop_threshold: 150

[fan]
pin: ar9

[heater_fan my_nozzle_fan]
pin: ar7
heater: extruder
heater_temp: 50.0

[mcu]
serial: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 5
max_z_accel: 100

[bed_screws]
screw1: 31.7, 31.7
screw2: 31.7, 201
screw3: 201, 201
screw4: 201, 31.7

[display]
lcd_type: st7920
cs_pin: ar27
sclk_pin: ar25
sid_pin: ar29
encoder_pins: ^ar23, ^ar17
click_pin: ^!ar35

[bltouch]
sensor_pin: ^ar18
control_pin: ar11
x_offset: -60.5
y_offset: -16.6
pin_move_time: 0.4
samples: 1
sample_retract_dist: 2

[safe_z_home]
home_xy_position: 177.5, 133.6
speed: 50.0
z_hop: 10.0
z_hop_speed: 10.0

[bed_mesh]
speed: 50
horizontal_move_z: 5
mesh_min: 31.7, 31.7
mesh_max: 189, 201
probe_count: 3, 3
fade_start: 1.0
mesh_pps: 2, 2

[screws_tilt_adjust]
screw1: 250, 48.3
screw1_name: front right screw
screw2: 250, 217.6
screw2_name: rear right screw
screw3: 92.2, 217.6
screw3_name: rear left screw
screw4: 92.2, 48.3
screw4_name: front left screw
horizontal_move_z: 10
speed: 50.0
screw_thread: CW-M3

[input_shaper]
#shaper_freq_x: 29.62
#shaper_freq_y: 29.41
shaper_freq_x: 37.56
shaper_freq_y: 41.09
shaper_type: mzv

[virtual_sdcard]
path: ~/klipper/gcodes

[display_status]

[pause_resume]

[gcode_macro PRINTER_OFF]
gcode:
    tuya_off

[include macros.cfg]

[output_pin beeper]
pin: EXP1_1
pwm: True
value: 0
shutdown_value: 0
cycle_time: 0.001 # PWM frequency : 0.001 = 1ms will give a tone of 1kHz (not pitch perfect).

[include timelapse.cfg]

# Common EXP1 / EXP2 (display) pins
[board_pins]
aliases:
    # Common EXP1 header found on many "all-in-one" ramps clones
    EXP1_1=ar37, EXP1_3=ar17, EXP1_5=ar23, EXP1_7=ar27, EXP1_9=<GND>,
    EXP1_2=ar35, EXP1_4=ar16, EXP1_6=ar25, EXP1_8=ar29, EXP1_10=<5V>,
    # EXP2 header
    EXP2_1=ar50, EXP2_3=ar31, EXP2_5=ar33, EXP2_7=ar49, EXP2_9=<GND>,
    EXP2_2=ar52, EXP2_4=ar53, EXP2_6=ar51, EXP2_8=ar41, EXP2_10=<RST>,
    # Pins EXP2_1, EXP2_6, EXP2_2 are also MISO, MOSI, SCK of bus "spi"
    # Note, some boards wire: EXP2_8=<RST>, EXP2_10=ar41
    # Marlin pin map
    ar0=PE0, ar1=PE1, ar2=PE4, ar3=PE5, ar4=PG5,
    ar5=PE3, ar6=PH3, ar7=PH4, ar8=PH5, ar9=PH6,
    ar10=PB4, ar11=PB5, ar12=PB6, ar13=PB7, ar14=PJ1,
    ar15=PJ0, ar16=PH1, ar17=PH0, ar18=PD3, ar19=PD2,
    ar20=PD1, ar21=PD0, ar22=PA0, ar23=PA1, ar24=PA2,
    ar25=PA3, ar26=PA4, ar27=PA5, ar28=PA6, ar29=PA7,
    ar30=PC7, ar31=PC6, ar32=PC5, ar33=PC4, ar34=PC3,
    ar35=PC2, ar36=PC1, ar37=PC0, ar38=PD7, ar39=PG2,
    ar40=PG1, ar41=PG0, ar42=PL7, ar43=PL6, ar44=PL5,
    ar45=PL4, ar46=PL3, ar47=PL2, ar48=PL1, ar49=PL0,
    ar50=PB3, ar51=PB2, ar52=PB1, ar53=PB0, ar54=PF0,
    ar55=PF1, ar56=PF2, ar57=PF3, ar58=PF4, ar59=PF5,
    ar60=PF6, ar61=PF7, ar62=PK0, ar63=PK1, ar64=PK2,
    ar65=PK3, ar66=PK4, ar67=PK5, ar68=PK6, ar69=PK7,
    analog0=PF0, analog1=PF1, analog2=PF2, analog3=PF3, analog4=PF4,
    analog5=PF5, analog6=PF6, analog7=PF7, analog8=PK0, analog9=PK1,
    analog10=PK2, analog11=PK3, analog12=PK4, analog13=PK5, analog14=PK6,
    analog15=PK7,
    # Additional aliases
    ml70=PG4, ml71=PG3, ml72=PJ2, ml73=PJ3, ml74=PJ7,
    ml75=PJ4, ml76=PJ5, ml77=PJ6, ml78=PE2, ml79=PE6,
    ml80=PE7, ml81=PD4, ml82=PD5, ml83=PD6, ml84=PH2,
    ml85=PH7

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	  0.097500, 0.077500, 0.082500
#*# 	  0.055000, -0.005000, -0.045000
#*# 	  0.037500, 0.002500, 0.020000
#*# x_count = 3
#*# y_count = 3
#*# mesh_x_pps = 2
#*# mesh_y_pps = 2
#*# algo = lagrange
#*# tension = 0.2
#*# min_x = 30.0
#*# max_x = 173.0
#*# min_y = 30.0
#*# max_y = 205.0
#*#
#*# [bltouch]
#*# z_offset = 1.301
#*#
#*# [extruder]
#*# control = pid
#*# pid_kp = 26.134
#*# pid_ki = 1.405
#*# pid_kd = 121.525
#*#
#*# [heater_bed]
#*# control = pid
#*# pid_kp = 61.15
#*# pid_ki = 10.39
#*# pid_kd = 247.78

```

macros.cfg
```
[gcode_macro _km_options]
variable_load_length: 420.0
variable_load_speed: 480.0
variable_menu_show_octoprint: False
variable_menu_show_sdcard: False
variable_menu_temperature: [
  {'name' : 'PLA',  'extruder' : 190.0, 'bed' : 40.0},
  {'name' : 'TPU', 'extruder' : 200.0, 'bed' : 40.0},
  {'name' : 'PETG',  'extruder' : 230.0, 'bed' : 65.0}]
variable_start_purge_length: 20
gcode: # This line is required by Klipper.
# Any code you put here will run at klipper startup, after the initialization
# for these macros. For example, you could uncomment the following line to
# automatically adjust your bed surface offsets to account for any changes made
# to your Z endstop or probe offset.
#  ADJUST_SURFACE_OFFSETS

# This line includes all the standard macros.
[include macros/*.cfg]
# Uncomment to include features that require specific hardware support.
# LCD menu support for features like bed surface selection and pause next layer.
[include macros/optional/lcd_menus.cfg]
# Optimized bed leveling
[include macros/optional/bed_mesh.cfg]

# The sections below here are required for the macros to work. If your config
# already has some of these sections you should merge the duplicates into one
# (or if they are identical just remove one of them).
[idle_timeout]
gcode:
  _KM_IDLE_TIMEOUT # This line must be in your idle_timeout section.

[respond]

[save_variables]
filename: ~/klipper/config/variables.cfg # UPDATE THIS FOR YOUR PATH!!!

# Uncomment the sections below if Fluidd complains (because it's confused).
#[gcode_macro CANCEL_PRINT]
#rename_existing: CANCEL_PRINT_FAKE_BASE
#gcode: CANCEL_PRINT_FAKE_BASE {rawparams}
```

**Comment by jschuh** [comment]
You don't have any bed surfaces defined in your `[gcode_macro _km_options]` section in `macros.cfg`. Adding a line like this will solve it by adding two available surfaces.

```
variable_bed_surfaces: ['smooth_1','texture_1']
```

I always set this up on my printers, so it looks like I don't have any error handling for this case. In retrospect, I should just add a default surface for when there's no custom config. I'll get to that sometime in the next day or so.

**Comment by scmanjarrez** [comment]
Sorry, I'm new with klipper, what are bed_surfaces?

**Comment by jschuh** [comment]
Oh, it's not a Klipper thing. It's [described here](https://github.com/jschuh/klipper-macros#bed-surface),  and emulates a [corresponding Prusa feature](https://help.prusa3d.com/article/steel-sheet-profiles_1955). It just lets you maintain custom offsets for as many build surfaces as you want, and switch between them. It's most useful for printers with no probe or non-contact probes, but I find it helps even with contact probes (e.g. BLTouch) because you typically want a different level of squish between something like a smooth versus textured PEI sheet.
