### ISSUE TITLE
[BUG] Unable to start print due to "bed_surfaces" error

### ISSUE THREAD

**Issue by Will-wastelander** [jschuh/klipper-macros#39]
**Describe the bug**
Please provide a clear and concise description of what the bug is.
When starting a print, I get the below error after bed_mesh is completed.
Printer is Ender 3 Pro w/ Duet 2 Wifi. Prints start w/o issue if klipper-macros is not loaded.

**Klipper error messages**
Paste any error Klipper error messages you observed when encountering the bug.
Error evaluating 'gcode_macro _apply_bed_surface_offset:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'bed_surfaces'

**Klipper config**
Paste any relevant sections from your Klipper config, or attach the full config if you prefer. Please also note any other macros you are including as part of your config.

printer.cfg has basics for functions.

```
[gcode_macro _km_options]
# These are examples of some likely customizations:
# Any sheets in the below list will be available with a configurable offset.
variable_bed_surfaces: ['smooth_1','texture_1']
# Length (in mm) of filament to load (bowden tubes will be longer).
variable_load_length: 250.0
# Hide the Octoprint LCD menu since I don't use it.
#variable_menu_show_octoprint: False
# Customize the filament menus (up to 10 entries).
#variable_menu_temperature: [
#  {'name' : 'PLA',  'extruder' : 200.0, 'bed' : 60.0},
#  {'name' : 'PETG', 'extruder' : 230.0, 'bed' : 85.0},
#  {'name' : 'ABS',  'extruder' : 245.0, 'bed' : 110.0, 'chamber' : 60}]
# Length of filament (in millimeters) to purge at print start.
variable_start_purge_length: 30 # This value works for most setups.
gcode: # This line is required by Klipper.
# Any code you put here will run at klipper startup, after the initialization
# for these macros. For example, you could uncomment the following line to
# automatically adjust your bed surface offsets to account for any changes made
# to your Z endstop or probe offset.
#  ADJUST_SURFACE_OFFSETS

# This line includes all the standard macros.
[include klipper-macros/*.cfg]
# Uncomment to include features that require specific hardware support.
# LCD menu support for features like bed surface selection and pause next layer.
#[include klipper-macros/optional/lcd_menus.cfg]
# Optimized bed leveling
[include klipper-macros/optional/bed_mesh.cfg]

# The sections below here are required for the macros to work.
[idle_timeout]
gcode:
  _KM_IDLE_TIMEOUT

```

**Comment by jschuh** [comment]
Usually that means there's a mistake in the `[save_variables]` section of your config. Unfortunately the portion of your config that you provided doesn't include the `[save_variables]` section, so I can't be sure, but you can find the required config sections at the bottom of the [Klipper Setup portion of the readme](https://github.com/jschuh/klipper-macros#klipper-setup).

Also, please ensure you're running the most current Klipper version, as [I landed a somewhat recent Klipper change](https://github.com/Klipper3d/klipper/pull/5922) to help diagnose misconfigured `[save_variables]`.

**Comment by Will-wastelander** [comment]
Looks like the variables.cfg file is empty. I copied the Klipper Setup section to my printer.cfg, I've included my complete printer.cfg this time.
```
[save_variables]
filename: ~/printer_data/variables.cfg # UPDATE THIS FOR YOUR PATH!!!
```

```
pi@E3Pro-mainsailos:~/printer_data $ ll variables.cfg
0 -rw-r--r-- 1 pi pi 0 Feb  4 20:44 variables.cfg
pi@E3Pro-mainsailos:~/printer_data $ cat variables.cfg
pi@E3Pro-mainsailos:~/printer_data $
```
printer.cfg
```
[include shell_command.cfg]
#[include mainsail.cfg]
#[include macros.cfg]
[include timelapse.cfg]
#[include klipper-macro.cfg]
#[include addons/inputshaper.cfg]
#[include addons/neopixel.cfg]
#[include addons/runout.cfg]
#[include addons/M20x.cfg]

# This file contains common pin mappings for Duet2 Eth/Wifi boards. To
# use this config, the firmware should be compiled for the SAM4E8E.

# See docs/Config_Reference.md for a description of parameters.

[temperature_sensor raspberry_pi]
sensor_type: temperature_host
min_temp: 10
max_temp: 100

[temperature_sensor mcu_temp]
sensor_type: temperature_mcu
min_temp: 0
max_temp: 100

[force_move]
enable_force_move: True

[mcu rpi]
serial: /tmp/klipper_host_mcu

# All customizations are documented in globals.cfg. Just copy a variable from
# there into the section below, and change the value to meet your needs.

[gcode_macro _km_options]
# These are examples of some likely customizations:
# Any sheets in the below list will be available with a configurable offset.
#variable_bed_surfaces: ['smooth_1','texture_1']
# Length (in mm) of filament to load (bowden tubes will be longer).
variable_load_length: 250.0
# Hide the Octoprint LCD menu since I don't use it.
#variable_menu_show_octoprint: False
# Customize the filament menus (up to 10 entries).
#variable_menu_temperature: [
#  {'name' : 'PLA',  'extruder' : 200.0, 'bed' : 60.0},
#  {'name' : 'PETG', 'extruder' : 230.0, 'bed' : 85.0},
#  {'name' : 'ABS',  'extruder' : 245.0, 'bed' : 110.0, 'chamber' : 60}]
# Length of filament (in millimeters) to purge at print start.
variable_start_purge_length: 30 # This value works for most setups.
gcode: # This line is required by Klipper.
# Any code you put here will run at klipper startup, after the initialization
# for these macros. For example, you could uncomment the following line to
# automatically adjust your bed surface offsets to account for any changes made
# to your Z endstop or probe offset.
#  ADJUST_SURFACE_OFFSETS

# This line includes all the standard macros.
[include klipper-macros/*.cfg]
# Uncomment to include features that require specific hardware support.
# LCD menu support for features like bed surface selection and pause next layer.
#[include klipper-macros/optional/lcd_menus.cfg]
# Optimized bed leveling
[include klipper-macros/optional/bed_mesh.cfg]

# The sections below here are required for the macros to work. If your config
# already has some of these sections you should merge the duplicates into one
# (or if they are identical just remove one of them).
[idle_timeout]
gcode:
  _KM_IDLE_TIMEOUT # This line must be in your idle_timeout section.

[pause_resume]

[respond]

[save_variables]
filename: ~/printer_data/variables.cfg # UPDATE THIS FOR YOUR PATH!!!

[virtual_sdcard]
path: ~/gcode_files # UPDATE THIS FOR YOUR PATH!!!

[display_status]

# Uncomment the sections below if Fluidd complains (because it's confused).
#[gcode_macro CANCEL_PRINT]
#rename_existing: CANCEL_PRINT_FAKE_BASE
#gcode: CANCEL_PRINT_FAKE_BASE {rawparams}

[stepper_x]
step_pin: PD6
dir_pin: !PD11
enable_pin: !PC6
microsteps: 16
rotation_distance: 40
endstop_pin: ^PC14
position_endstop: 0
position_max: 250
homing_speed: 125

[tmc2660 stepper_x]
cs_pin: PD14
spi_bus: usart1
run_current: 0.495
sense_resistor: 0.051
interpolate: true

[stepper_y]
step_pin: PD7
dir_pin: !PD12
enable_pin: !PC6
microsteps: 16
rotation_distance: 40
endstop_pin: ^PA2
position_endstop: 0
position_max: 210
homing_speed: 50

[tmc2660 stepper_y]
cs_pin: PC9
spi_bus: usart1
run_current: 0.495
sense_resistor: 0.051
interpolate: true

[stepper_z]
step_pin: PD8
dir_pin: PD13
enable_pin: !PC6
microsteps: 16
rotation_distance: 8
#endstop_pin: ^PD29
endstop_pin: probe:z_virtual_endstop
position_min: -3.5
position_max: 200

[tmc2660 stepper_z]
cs_pin: PC10
spi_bus: usart1
run_current: 0.495
sense_resistor: 0.051
interpolate: true

[stepper_z1]
step_pin: PD4
dir_pin: !PD9
enable_pin: !PC6
microsteps: 16
rotation_distance: 8

[tmc2660 stepper_z1]
cs_pin: PC25
spi_bus: usart1
run_current: 0.495
sense_resistor: 0.051
interpolate: true

[extruder]
step_pin: PD5
dir_pin: !PA1
enable_pin: !PC6
microsteps: 16
#rotation_distance: 33.500
rotation_distance: 22.95
gear_ratio: 50:17
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: !PA20
sensor_type: ATC Semitec 104GT-2
sensor_pin: PC15
#control: pid
#pid_Kp: 22.2
#pid_Ki: 1.08
#pid_Kd: 114
min_temp: 0
max_temp: 275

[tmc2660 extruder]
cs_pin: PC17
spi_bus: usart1
#run_current: 1.000
run_current: 0.565
sense_resistor: 0.051
interpolate: true

[heater_bed]
heater_pin: !PA19
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC13
#control: watermark
min_temp: 0
max_temp: 130

[fan]
pin: PC23  # FAN0

[heater_fan heatbreak_cooling_fan]
pin: PC26  # FAN1
heater: extruder
heater_temp: 45
#fan_speed: 1.0
fan_speed: 0.4

[heater_fan board_cooling_fan]
pin: PA0  # FAN2

[filament_switch_sensor Filament]
pause_on_runout: false #pause handled by macro
runout_gcode:
  M600 #calls a macro with the name M600 (so it can be called by slicers too)
switch_pin: PD10

[mcu]
serial: /dev/serial/by-id/usb-Klipper_sam4e8e_00323053354141543134303335303139-if00

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 5
max_z_accel: 100 

[static_digital_output onboard_led]
pins: !PC2

#====================================================================
# BLTOUCH
#====================================================================
[bltouch]
sensor_pin: ^PC1
control_pin: PC3
#set_output_mode: 5V
pin_move_time: 0.675
stow_on_each_sample: True
probe_with_touch_mode: True
pin_up_touch_mode_reports_triggered: False
x_offset: -42.0
y_offset: -8.0
#z_offset: 1.33
speed: 10
lift_speed: 20
samples: 2
sample_retract_dist:5
samples_tolerance_retries: 3

[safe_z_home]
home_xy_position: 117, 117
speed: 150
z_hop: 10
z_hop_speed: 20

[bed_mesh]
algorithm: bicubic
speed: 150
horizontal_move_z: 10
#mesh_min: 35,35
#mesh_max: 220,220
mesh_min: 30,30
mesh_max: 195,195
probe_count: 7,7
fade_end: 10
mesh_pps: 2,2
fade_start: 0.6
fade_end: 10
fade_target: 0
; relative_reference_index = ()(x points * y points) - 1) / 2
relative_reference_index: 24

[z_tilt]
# Ender screw edge offsets are 35,35
# z_positions = IRL position of the stepper itself, in nozzle coords so will be off the bed at the back
# points = probe locations = nozzle + probe offset
# stepper X are 30mm off bed edge left & right
# stepper Y is 80 off the back when nozzle at Y=230 = 230+80
z_positions:
	-30, 310       ##Stepper Location Z0, as if the nozzle were in the screw
	265, 310       ##Stepper Location Z1, as if the nozzle were in the screw
points:
    73, 117
    238, 117
speed: 200
horizontal_move_z: 10
retries: 20
#retry_tolerance:0.010
retry_tolerance:0.005

[bed_screws]
screw1: 30,30
screw1_name: front left screw
screw2: 30,205
screw2_name: rear left screw
screw3: 195,205
screw3_name: rear right screw
screw4: 195,35
screw4_name: front right screw

#[screws_tilt_adjust]
#screw1: 74,47
#screw1_name: front left screw
#screw2: 245, 47
#screw2_name: front right screw
#screw3: 245, 217
#screw3_name: rear right screw
#screw4: 74,217
#screw4_name: rear left screw
#screw_thread: CW-M4

[screws_tilt_adjust]
screw1: 75,205
screw1_name: rear left screw
screw2: 75,35
screw2_name: front left screw
screw3: 245,205
screw3_name: rear right screw
screw4: 245,35
screw4_name: front right screw
horizontal_move_z: 5
speed: 50
screw_thread: CW-M4

[gcode_arcs]
resolution: 0.05

#[output_pin BEEPER_pin]
#pin: PC5
##   Beeper pin. This parameter must be provided.
##   ar37 is the default RAMPS/MKS pin.
##pwm: True
#pwm: False
##   A piezo beeper needs a PWM signal, a DC buzzer doesn't.
#value: 0
##   Silent at power on, set to 1 if active low.
#shutdown_value: 0
##   Disable at emergency shutdown (no PWM would be available anyway).
##cycle_time: 0.001
##   Default PWM frequency : 0.001 = 1ms will give a tone of 1kHz
##   Although not pitch perfect.

#[gcode_macro LIGHTS_ON]
#description: Helper: Light on
#gcode:
#  SET_PIN PIN=lights VALUE=1
    
#[gcode_macro LIGHTS_OFF]
#description: Helper: Light off
#gcode:
#  #SET_LED LED="lights" RED=0 GREEN=0 BLUE=0 SYNC=0 TRANSMIT=1
#  STOP_LED_EFFECTS

[gcode_macro DUMP_VARIABLES]
gcode:
    {% set filter_name = params.NAME|default('')|string|lower %}
    {% set filter_value = params.VALUE|default('')|string|lower %}
    {% set show_cfg = params.SHOW_CFG|default(0)|int %}
    
    {% set out = [] %}

    {% for key1 in printer %}
        {% for key2 in printer[key1] %}
            {% if (show_cfg or not (key1|lower == 'configfile' and key2|lower in ['config', 'settings'])) and (filter_name in key1|lower or filter_name in key2|lower) and filter_value in printer[key1][key2]|string|lower %}
                {% set dummy = out.append("printer['%s'].%s = %s" % (key1, key2, printer[key1][key2])) %}
            {% endif %}
        {% else %}
            {% if filter_name in key1|lower and filter_value in printer[key1]|string|lower %}
                {% set dummy = out.append("printer['%s'] = %s" % (key1, printer[key1])) %}
            {% endif %}
        {% endfor %}
    {% endfor %}
    
    {action_respond_info(out|join("\n"))}

[delayed_gcode bed_mesh_init]
initial_duration: .01
gcode:
  BED_MESH_PROFILE LOAD=default

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [extruder]
#*# control = pid
#*# pid_kp = 25.344
#*# pid_ki = 1.280
#*# pid_kd = 125.453
#*#
#*# [heater_bed]
#*# control = pid
#*# pid_kp = 68.919
#*# pid_ki = 1.324
#*# pid_kd = 896.812
#*#
#*# [bltouch]
#*# z_offset = 1.384
```

**Comment by Will-wastelander** [comment]
Here is the klipper.log of the failure, if it helps.

```
Mesh Bed Leveling Complete
save_config: set [bed_mesh default] version = 1
save_config: set [bed_mesh default] points =
  -0.087500, -0.036250, 0.063750, 0.101250, 0.192500, 0.203750, 0.241250
  -0.146250, -0.085000, 0.012500, 0.045000, 0.143750, 0.168750, 0.211250
  -0.128750, -0.071250, 0.017500, 0.062500, 0.152500, 0.178750, 0.213750
  -0.140000, -0.108750, -0.018750, 0.000000, 0.106250, 0.126250, 0.210000
  -0.166250, -0.072500, 0.022500, 0.075000, 0.166250, 0.202500, 0.237500
  -0.121250, -0.076250, 0.002500, 0.018750, 0.121250, 0.142500, 0.252500
  -0.071250, 0.003750, 0.106250, 0.137500, 0.230000, 0.258750, 0.290000
save_config: set [bed_mesh default] x_count = 7
save_config: set [bed_mesh default] y_count = 7
save_config: set [bed_mesh default] mesh_x_pps = 2
save_config: set [bed_mesh default] mesh_y_pps = 2
save_config: set [bed_mesh default] algo = bicubic
save_config: set [bed_mesh default] tension = 0.2
save_config: set [bed_mesh default] min_x = 30.0
save_config: set [bed_mesh default] max_x = 195.0
save_config: set [bed_mesh default] min_y = 30.0
save_config: set [bed_mesh default] max_y = 195.0
Bed Mesh state has been saved to profile [default]
for the current session.  The SAVE_CONFIG command will
update the printer config file and restart the printer.
Error evaluating 'gcode_macro _apply_bed_surface_offset:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'bed_surfaces'
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 61, in render
    return str(self.template.render(context))
  File "/home/pi/klippy-env/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/pi/klippy-env/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/pi/klippy-env/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 3, in top-level template code
  File "/home/pi/klippy-env/lib/python3.9/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'bed_surfaces'
Error evaluating 'gcode_macro _apply_bed_surface_offset:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'bed_surfaces'

Error evaluating 'gcode_macro _apply_bed_surface_offset:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'bed_surfaces'

Exiting SD card print (position 1361)
```

**Comment by jschuh** [comment]
It sure seems like nothing is getting written to your `save_variables` file, since the macros should always write some state at startup. Could you try running this command in the Klipper console:

```
SAVE_VARIABLE VARIABLE=test VALUE='"test"'
```

Check immediately afterward to see if it's written to the file, and if there's anything in the Klipper log. The log message on a `save_variables` write failure should include the text: `Unable to save variable`

**Comment by Will-wastelander** [comment]
Ran command, and get this.

```
pi@E3Pro-mainsailos:~ $ cat printer_data/variables.cfg
[Variables]
test = 'test'
```

**Comment by jschuh** [comment]
Hm... that means `_INIT_SURFACES` just isn't running; or worse, `INIT_GLOBALS` either isn't running or isn't completing. That would actually break a lot of things, since it performs all the initialization for the macros.

Are you getting any Klipper console messages at startup? (I.e. after restarting in Mainsail via: Power button -> Klipper Control: Restart.)

If there are no errors in the console then maybe there's something about your system where the `initial_duration` on `INIT_GLOBALS` is too short. I haven't heard of anyone else hitting that issue, but I have observed that if the duration is too low Klipper won't fire the event. It's in `globals.cfg` and looks like this:

```
[delayed_gcode INIT_GLOBALS]
# This runs once at startup and initializes all macros.
initial_duration: 0.0001
```

You could try changing `initial_duration` to something larger like `0.01` and then restarting and seeing if anything new is written to the `variables.cfg`. If that solves it, I'll land a change loosening the initial duration.

Failing that, the most likely possibility is a conflict with some other macros you're loading. Unfortunately, that's the point where I would probably just give up. The Klipper macro system isn't really designed for cleanly integrating multiple sets of macros, and conflicts are common enough. I have been slowly renaming things with unique prefixes to reduce the chances of a breaking collision, but that's still no guarantee of a fix.

Also, I noticed that you have the `variable_bed_surfaces` commented out. That shouldn't be a problem, but you can try uncommenting, restarting Klipper, and seeing if it works.

**Comment by Will-wastelander** [comment]
No change in the variables.cfg file being written to. I have tried with and w/o the variable_bed_surfaces_ commented out.

I just checked the logs, using a clean log file, and found an error about "max_extrude_only_distance" After looking at my printer.cfg I see that setting was missing. I added it, and now see the variable.cfg file being written to.

I will test and report back.

**Comment by xyleth** [comment]
I had this exact problem.  In the end, the issue was max_extrude_only_distance being set shorter than the load_length specified in the macros, and I only found that out by scrolling through the klipper log.  No console errors were thrown.

Setting max_extrude_only_distance > load_length fixed the problem and the bed_surfaces dict was written to the variables file properly.

**Comment by Will-wastelander** [comment]
I can confirm that adding max_extrude_only_distance to my [extruder] config has resolved the issue.

**Comment by jschuh** [comment]
Wow, I just put a bad entry as a test for one of my configs and I'm not seeing startup errors anymore either. Something must have changed in Klipper or Mainsail. I'll have to dig into it and see.

That stated, you can directly run `_CHECK_GLOBALS` to throw an error on configuration issues. I'll add something to the readme on using it for troubleshooting, and maybe add it to `PRINT_START` just to be safe.

Sorry you had the hassle, but at least I should be able to save anyone else from having the same problem in the future.

**Comment by Will-wastelander** [comment]
Helping a project that I use, is never a hassle. Even if it's a config
issue on my side, LOL. I'm just glad it was able to be resolved quickly.

Thanks for the quick responses!
